# Generated by Django 5.2.16 on 2026-07-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Platform_Core", "0011_accounting_periods"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("code", models.CharField(max_length=40)),
                ("period_type", models.CharField(choices=[("annual", "Annual"), ("quarterly", "Quarterly"), ("monthly", "Monthly"), ("custom", "Custom")], default="annual", max_length=20)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("closed", "Closed"), ("archived", "Archived")], default="draft", max_length=20)),
                ("control_mode", models.CharField(choices=[("hard", "Hard Control"), ("soft", "Soft Control")], default="hard", max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("currency", models.CharField(default="KES", max_length=10)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="budgets", to="Platform_Core.tenantbranch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_budgets", to=settings.AUTH_USER_MODEL)),
                ("financial_year", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="budgets", to="Platform_Core.financialyear")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="budgets", to="Platform_Core.tenant")),
            ],
            options={
                "ordering": ["tenant__name", "-start_date", "name"],
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cost_center", models.CharField(max_length=120)),
                ("project_code", models.CharField(blank=True, max_length=80)),
                ("period_year", models.PositiveIntegerField(default=2026)),
                ("period_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("allocated_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("committed_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("obligated_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("actual_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="budget_lines", to="Platform_Core.account")),
                ("budget", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="SL_Budgeting.budget")),
            ],
            options={
                "ordering": ["budget__name", "cost_center", "account__code", "period_year", "period_month"],
                "unique_together": {("budget", "account", "cost_center", "project_code", "period_year", "period_month")},
            },
        ),
        migrations.CreateModel(
            name="BudgetCommitment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(choices=[("requisition", "Requisition"), ("purchase_order", "Purchase Order"), ("bill", "Bill"), ("manual", "Manual")], default="requisition", max_length=30)),
                ("source_reference", models.CharField(max_length=80)),
                ("state", models.CharField(choices=[("committed", "Committed"), ("obligated", "Obligated"), ("actual", "Actual"), ("released", "Released")], default="committed", max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("budget_line", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="commitments", to="SL_Budgeting.budgetline")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="budget_commitments_created", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="budget_commitments", to="Platform_Core.tenant")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BudgetCheckLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requisition_reference", models.CharField(blank=True, max_length=80)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("result", models.CharField(choices=[("pass", "Pass"), ("warn", "Warn"), ("block", "Block")], max_length=20)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("budget_line", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="check_logs", to="SL_Budgeting.budgetline")),
                ("checked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="budget_checks_run", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="budget_check_logs", to="Platform_Core.tenant")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]

