[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "a4>=0.2.7",
    "arabic-reshaper>=3.0.1",
    "celery>=5.6.3",
    "channels>=4.3.2",
    "crispy-bootstrap5>=2026.3",
    "dj-database-url>=3.1.2",
    "django>=5.2.16",
    "django-admin-rangefilter>=0.13.5",
    "django-allauth>=65.18.0",
    "django-cors-headers>=4.9.0",
    "django-crispy-forms>=2.6",
    "django-extensions>=4.1",
    "django-filter>=26.1",
    "django-guardian>=3.3.2",
    "django-import-export>=4.4.1",
    "django-phonenumber-field>=8.4.0",
    "django-role-permissions>=3.2.0",
    "django-unfold>=0.91.0",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "gunicorn>=26.0.0",
    "humanize>=4.16.0",
    "lxml>=6.1.1",
    "numpy>=2.4.6",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "phonenumbers>=9.0.34",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pypdf>=6.14.2",
    "pyserial>=3.5",
    "pytesseract>=0.3.13",
    "python-bidi>=0.6.11",
    "python-dotenv>=1.2.2",
    "qrcode>=8.2",
    "redis>=8.0.1",
    "reportlab>=5.0.0",
    "requests>=2.34.2",
    "social-auth-app-django>=6.0.0",
    "svglib>=2.0.2",
    "tablib>=3.9.0",
    "tenacity>=9.1.4",
    "toml>=0.10.2",
    "tzlocal>=5.4.4",
    "whitenoise>=6.12.0",
    "xhtml2pdf>=0.2.14",
]
