# Generated by Codex on 2026-08-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Platform_Core", "0028_organization_membership"),
        ("SL_HR", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payperiod",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pay_periods",
                to="Platform_Core.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payperiod",
            unique_together={("tenant", "name", "period_start", "period_end")},
        ),
    ]
