from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Platform_Core", "0030_tenant_offboarding_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(editable=False, max_length=24, unique=True)),
                ("public_token", models.CharField(default="", editable=False, max_length=40)),
                ("requester_name", models.CharField(blank=True, max_length=150)),
                ("requester_email", models.EmailField(max_length=254)),
                ("requester_phone", models.CharField(blank=True, max_length=50)),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("priority", models.CharField(choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")], default="normal", max_length=20)),
                ("status", models.CharField(choices=[("new", "New"), ("open", "Open"), ("pending", "Pending"), ("resolved", "Resolved"), ("closed", "Closed")], default="new", max_length=20)),
                ("source_page", models.CharField(blank=True, max_length=255)),
                ("source_channel", models.CharField(default="api", max_length=50)),
                ("external_reference", models.CharField(blank=True, max_length=120)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("first_response_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_tickets", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tickets", to="Platform_Core.tenant")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TicketFormSchema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                ("schema", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("allowed_mime_types", models.JSONField(blank=True, default=list)),
                ("max_file_size_mb", models.PositiveIntegerField(default=10)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ticketing_form_schemas", to="Platform_Core.tenant")),
            ],
            options={"ordering": ["tenant__name", "name"], "unique_together": {("tenant", "slug")}},
        ),
        migrations.CreateModel(
            name="TicketEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=50)),
                ("summary", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_public", models.BooleanField(default=True)),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="SL_Ticketing.ticket")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="TicketingInboxConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allowed_domains", models.JSONField(blank=True, default=list)),
                ("portal_access_policy", models.CharField(choices=[("email_match", "Email + Ticket ID"), ("secure_token", "Secure Token Link"), ("account_only", "Account Only")], default="email_match", max_length=30)),
                ("brand_settings", models.JSONField(blank=True, default=dict)),
                ("widget_settings", models.JSONField(blank=True, default=dict)),
                ("email_settings", models.JSONField(blank=True, default=dict)),
                ("webhook_settings", models.JSONField(blank=True, default=dict)),
                ("require_cors_origin", models.BooleanField(default=True)),
                ("allow_anonymous_tracking", models.BooleanField(default=True)),
                ("allow_requester_close", models.BooleanField(default=True)),
                ("tenant", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="ticketing_config", to="Platform_Core.tenant")),
            ],
            options={"ordering": ["tenant__name"]},
        ),
        migrations.CreateModel(
            name="TicketingWebhookEndpoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("target_url", models.URLField()),
                ("signing_secret", models.CharField(blank=True, default="", max_length=120)),
                ("subscribed_events", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ticketing_webhook_endpoints", to="Platform_Core.tenant")),
            ],
            options={"ordering": ["tenant__name", "name"], "unique_together": {("tenant", "name")}},
        ),
        migrations.CreateModel(
            name="TicketRoutingRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("target_status", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("assign_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ticketing_rules_assigned", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ticketing_routing_rules", to="Platform_Core.tenant")),
            ],
            options={"ordering": ["tenant__name", "priority", "name"], "unique_together": {("tenant", "name")}},
        ),
        migrations.CreateModel(
            name="TicketingApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("key_type", models.CharField(choices=[("public", "Public"), ("secret", "Secret")], max_length=20)),
                ("token_prefix", models.CharField(db_index=True, max_length=24)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ticketing_api_keys", to="Platform_Core.tenant")),
            ],
            options={"ordering": ["tenant__name", "name"], "unique_together": {("tenant", "name", "key_type")}},
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_type", models.CharField(choices=[("requester", "Requester"), ("agent", "Agent"), ("system", "System")], default="requester", max_length=20)),
                ("author_name", models.CharField(blank=True, max_length=150)),
                ("message", models.TextField()),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("is_public", models.BooleanField(default=True)),
                ("author_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ticket_messages", to=settings.AUTH_USER_MODEL)),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="SL_Ticketing.ticket")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="TicketWebhookDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=50)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_excerpt", models.TextField(blank=True)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("was_successful", models.BooleanField(default=False)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("endpoint", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="SL_Ticketing.ticketingwebhookendpoint")),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="webhook_deliveries", to="SL_Ticketing.ticket")),
            ],
            options={"ordering": ["-attempted_at"]},
        ),
        migrations.AddField(
            model_name="ticket",
            name="form_schema",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tickets", to="SL_Ticketing.ticketformschema"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["tenant", "status"], name="SL_Ticketin_tenant__b61fa1_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["tenant", "requester_email"], name="SL_Ticketin_tenant__d4a9df_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["tenant", "created_at"], name="SL_Ticketin_tenant__b123a1_idx"),
        ),
    ]
