import { useState } from 'react';
import { Link } from 'wouter';
import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, CalendarClock, CheckCircle2, Clock3, Mail, MessageSquare, Phone, Target } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';

function useCRMDashboard() {
  return useQuery({ queryKey: ['crm-dashboard'], queryFn: async () => { const response = await fetch('/api/crm/dashboard/', { headers: { Authorization: `Token ${localStorage.getItem('sl-erp-token')}` } }); if (!response.ok) throw new Error(`${response.status}`); return response.json(); }, staleTime: 60_000 });
}

const stageColors: Record<string, string> = { new: 'bg-slate-400', contacted: 'bg-blue-500', proposal: 'bg-purple-500', negotiation: 'bg-orange-500', won: 'bg-emerald-500', lost: 'bg-red-400' };
const stageBadges: Record<string, string> = { new: 'bg-slate-100 text-slate-700', contacted: 'bg-blue-100 text-blue-800', proposal: 'bg-purple-100 text-purple-800', negotiation: 'bg-orange-100 text-orange-800', won: 'bg-emerald-100 text-emerald-800', lost: 'bg-red-100 text-red-800' };
const activityIcons: Record<string, React.ReactNode> = { call: <Phone className="h-3.5 w-3.5" />, email: <Mail className="h-3.5 w-3.5" />, meeting: <CalendarClock className="h-3.5 w-3.5" />, note: <MessageSquare className="h-3.5 w-3.5" />, task: <CheckCircle2 className="h-3.5 w-3.5" /> };

function money(value: number | string | null | undefined) { return `KES ${Number(value ?? 0).toLocaleString()}`; }
function dateTime(value?: string | null) { if (!value) return 'No date'; const date = new Date(value); return `${date.toLocaleDateString(undefined, { day: 'numeric', month: 'short' })} · ${date.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}`; }

function RecordDrawer({ record, close }: { record: any; close: () => void }) {
  if (!record) return null;
  const item = record.item;
  const activity = record.kind === 'activity';
  return <Sheet open onOpenChange={(open) => !open && close()}><SheetContent side="right" className="w-full sm:max-w-xl"><SheetHeader><SheetTitle>{activity ? 'Activity details' : 'Opportunity details'}</SheetTitle><SheetDescription>Live CRM record and available next actions.</SheetDescription></SheetHeader><div className="mt-5 rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{item.summary || item.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.contact_name || item.organisation_name || 'Unlinked record'}</p></div>{!activity && <span className={`rounded border px-2 py-1 text-[10px] font-semibold uppercase ${stageBadges[item.stage] ?? 'bg-secondary'}`}>{item.stage_display || item.stage}</span>}</div><dl className="mt-4 grid grid-cols-2 gap-3 border-t pt-3 text-sm"><div><dt className="text-xs text-muted-foreground">{activity ? 'Due' : 'Expected close'}</dt><dd className="mt-1 font-medium">{dateTime(item.date || item.expected_close_date)}</dd></div><div><dt className="text-xs text-muted-foreground">Owner</dt><dd className="mt-1 font-medium">{item.assigned_to_name || item.created_by_name || 'Unassigned'}</dd></div>{!activity && <div><dt className="text-xs text-muted-foreground">Value</dt><dd className="mt-1 font-medium">{money(item.value)}</dd></div>}{activity && <div><dt className="text-xs text-muted-foreground">Status</dt><dd className="mt-1 font-medium capitalize">{item.status || 'Open'}</dd></div>}</dl></div><div className="mt-4 flex gap-2"><Link href={activity ? '/crm/follow-ups' : '/crm/opportunities'}><Button size="sm">Open full record</Button></Link>{activity && item.status !== 'completed' ? <Link href="/crm/follow-ups"><Button size="sm" variant="outline">Complete / reschedule</Button></Link> : null}</div></SheetContent></Sheet>;
}

export default function CRMDashboard() {
  const { data, isLoading } = useCRMDashboard();
  const [record, setRecord] = useState<any>(null);
  if (isLoading) return <div className="p-12 text-center text-sm text-muted-foreground animate-pulse">Loading CRM dashboard…</div>;
  const summary = data?.summary ?? {};
  const stages: any[] = data?.pipeline_stages ?? [];
  const recent: any[] = data?.recent_follow_ups ?? [];
  const queues = data?.priority_queues ?? {};
  const reps: any[] = data?.performance_by_owner ?? [];
  const priorityGroups = [
    { label: 'Overdue follow-ups', count: (queues.overdue_follow_ups ?? []).length, items: queues.overdue_follow_ups ?? [], icon: <Phone className="h-3.5 w-3.5" />, tone: 'bg-rose-100 text-rose-700', kind: 'activity' },
    { label: 'Due today', count: (queues.upcoming_follow_ups ?? []).filter((item: any) => new Date(item.date).toDateString() === new Date().toDateString()).length, items: queues.upcoming_follow_ups ?? [], icon: <CalendarClock className="h-3.5 w-3.5" />, tone: 'bg-amber-100 text-amber-700', kind: 'activity' },
    { label: 'Closing soon (7 days)', count: (queues.closing_soon ?? []).length, items: queues.closing_soon ?? [], icon: <Target className="h-3.5 w-3.5" />, tone: 'bg-blue-100 text-blue-700', kind: 'opportunity' },
  ];
  const maxRepValue = Math.max(1, ...reps.map((rep) => Number(rep.pipeline_value ?? 0)));
  return <div className="space-y-4"><header className="flex flex-wrap items-end justify-between gap-3 border-b pb-3"><div><h1 className="text-2xl font-semibold tracking-tight">CRM</h1><p className="mt-1 text-sm text-muted-foreground">Customer relationships, sales pipeline and team activity.</p></div><div className="flex gap-2"><Link href="/crm/follow-ups"><Button size="sm" variant="outline">Log Activity</Button></Link><Link href="/crm/opportunities"><Button size="sm">Add Opportunity</Button></Link></div></header>
    <section className="grid grid-cols-2 gap-3 border-y py-3 md:grid-cols-5">{[['Pipeline Value', money(summary.pipeline_value)], ['Won This Month', money(summary.won_value_this_month)], ['Open Deals', summary.open_opportunities ?? 0], ['Overdue Follow-ups', summary.overdue_follow_ups ?? 0], ['Closing Soon (7 days)', summary.closing_soon ?? 0]].map(([label, value]) => <div key={String(label)} className="border-l px-3 first:border-l-0"><div className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">{label}</div><div className="mt-1 text-lg font-semibold">{value}</div></div>)}</section>
    <div className="grid gap-4 xl:grid-cols-[1.3fr_0.7fr]"><Card><CardHeader className="flex-row items-center justify-between border-b py-3"><CardTitle className="text-sm font-semibold">Pipeline by Stage</CardTitle><Link href="/crm/opportunities" className="text-xs text-primary hover:underline">View deals</Link></CardHeader><CardContent className="p-4"><div className="flex h-36 items-end justify-around gap-2 border-b px-2">{stages.map((stage: any) => <div key={stage.stage} className="flex h-full w-full flex-col items-center justify-end gap-1"><div className={`w-8 max-w-full rounded-t ${stageColors[stage.stage] ?? 'bg-primary'}`} style={{ height: `${Math.max(3, Math.min(92, ((stage.value ?? 0) / Math.max(1, summary.pipeline_value ?? 1)) * 92))}%` }} /><span className="text-xs font-semibold">{stage.count}</span><span className="truncate text-[10px] text-muted-foreground">{stage.label}</span><span className="truncate text-[10px] text-muted-foreground">{money(stage.value)}</span></div>)}</div></CardContent></Card>
      <Card><CardHeader className="flex-row items-center justify-between border-b py-3"><CardTitle className="text-sm font-semibold">Today's Priorities</CardTitle><Link href="/crm/follow-ups" className="text-xs text-primary hover:underline">View all</Link></CardHeader><CardContent className="divide-y p-0">{priorityGroups.map((group) => <button key={group.label} type="button" onClick={() => group.items[0] && setRecord({ kind: group.kind, item: group.items[0] })} className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-muted/30"><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full ${group.tone}`}>{group.icon}</span><span className="flex-1 text-sm font-medium">{group.count} {group.label}</span><span className="text-muted-foreground">›</span></button>)}</CardContent></Card></div>
    <div className="grid gap-4 xl:grid-cols-[1.1fr_0.9fr]"><Card><CardHeader className="border-b py-3"><CardTitle className="text-sm font-semibold">Recent Activity</CardTitle></CardHeader><CardContent className="divide-y p-0">{recent.slice(0, 2).map((item: any) => <button key={item.id} type="button" onClick={() => setRecord({ kind: 'activity', item })} className="flex w-full items-start gap-3 px-4 py-3 text-left hover:bg-muted/30"><span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-muted text-muted-foreground">{activityIcons[item.type] ?? <MessageSquare className="h-3.5 w-3.5" />}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{item.summary}</span><span className="block truncate text-xs text-muted-foreground">{item.contact_name || item.organisation_name || 'Unlinked record'}</span></span><span className="shrink-0 whitespace-nowrap text-[11px] text-muted-foreground">{dateTime(item.date)}</span></button>)}</CardContent></Card><Card><CardHeader className="flex-row items-center justify-between border-b py-3"><CardTitle className="text-sm font-semibold">Top Performing Sales Reps</CardTitle><Link href="/crm/performance" className="text-xs text-primary hover:underline">View report</Link></CardHeader><CardContent className="divide-y p-0">{reps.slice(0, 3).map((rep: any, index: number) => <div key={rep.assigned_to_id ?? rep.owner_name} className="flex items-center gap-3 px-4 py-3 text-sm"><span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-muted text-xs">{index + 1}</span><span className="w-24 shrink-0 font-medium truncate">{rep.owner_name}</span><span className="h-1.5 flex-1 overflow-hidden rounded-full bg-muted"><span className="block h-full rounded-full bg-emerald-500" style={{ width: `${(Number(rep.pipeline_value ?? 0) / maxRepValue) * 100}%` }} /></span><span className="shrink-0 text-xs text-muted-foreground">{money(rep.pipeline_value)}</span></div>)}</CardContent></Card></div>
    <RecordDrawer record={record} close={() => setRecord(null)} /></div>;
}
