from django.urls import path
from . import views

urlpatterns = [
    path("dashboard/",                              views.WeighbridgeDashboardView.as_view(),        name="wb-dashboard"),
    path("transactions/",                           views.TransactionListCreateView.as_view(),       name="wb-transactions"),
    path("transactions/export/csv/",               views.TransactionExportCSVView.as_view(),        name="wb-transactions-export-csv"),
    path("reports/document/",                      views.WeighbridgeReportDocumentView.as_view(),    name="wb-report-document"),
    path("transactions/workflow-context/",          views.WorkflowContextView.as_view(),             name="wb-workflow-context"),
    path("transactions/capture-weight/",            views.CaptureWeightView.as_view(),               name="wb-capture-weight"),
    path("transactions/<int:pk>/",                  views.TransactionDetailView.as_view(),           name="wb-transaction-detail"),
    path("transactions/<int:pk>/approve/",          views.TransactionApproveView.as_view(),          name="wb-transaction-approve"),
    path("transactions/<int:pk>/recall/",           views.TransactionRecallView.as_view(),           name="wb-transaction-recall"),
    path("transactions/<int:pk>/reject/",           views.TransactionRejectView.as_view(),           name="wb-transaction-reject"),
    path("transactions/<int:pk>/email-receipt/",   views.TransactionEmailReceiptView.as_view(),     name="wb-transaction-email-receipt"),
    path("transactions/<int:pk>/receipt/",         views.TransactionReceiptDocumentView.as_view(),  name="wb-transaction-receipt"),
    path("transactions/<int:pk>/receive-payment/", views.TransactionReceivePaymentView.as_view(),   name="wb-transaction-receive-payment"),
    path("branches/",                               views.BranchListView.as_view(),                            name="wb-branches"),
    path("vehicle-types/",                          views.VehicleTypeListView.as_view(),                       name="wb-vehicle-types"),
    path("vehicle-types/<int:pk>/",                 views.VehicleTypeCreateUpdateDeleteView.as_view(),         name="wb-vehicle-type-detail"),
    path("weighing-operation-types/",               views.WeighingOperationTypeListCreateView.as_view(),       name="wb-weighing-operation-types"),
    path("weighing-operation-types/<int:pk>/",      views.WeighingOperationTypeDetailView.as_view(),           name="wb-weighing-operation-type-detail"),
    path("items/",                                  views.ItemListCreateView.as_view(),                        name="wb-items"),
    path("items/<int:pk>/",                         views.ItemDetailView.as_view(),                            name="wb-item-detail"),
    path("indicator-configs/",                      views.IndicatorConfigListCreateView.as_view(),             name="wb-indicator-configs"),
    path("indicator-configs/<int:pk>/",             views.IndicatorConfigDetailView.as_view(),                 name="wb-indicator-config-detail"),
    path("indicator-configs/<int:pk>/test/",        views.IndicatorConfigTestConnectionView.as_view(),         name="wb-indicator-config-test"),
    path("discounts/",                              views.CustomerVehicleTypeDiscountListCreateView.as_view(), name="wb-discounts"),
    path("discounts/<int:pk>/",                     views.CustomerVehicleTypeDiscountDetailView.as_view(),     name="wb-discount-detail"),
    path("customers/",                              views.CustomerListCreateView.as_view(),      name="wb-customers"),
    path("customers/bulk-action/",                  views.CustomerBulkActionView.as_view(),      name="wb-customers-bulk-action"),
    path("customers/<int:pk>/",                     views.CustomerDetailView.as_view(),          name="wb-customer-detail"),
    path("vehicles/",                               views.VehicleListCreateView.as_view(),       name="wb-vehicles"),
    path("vehicles/<int:pk>/",                      views.VehicleDetailView.as_view(),           name="wb-vehicle-detail"),
    path("live-weight/",                            views.LiveWeightView.as_view(),              name="wb-live-weight"),
    # ── Overweight Surveillance ───────────────────────────────────────────────
    path("overweight-events/",                      views.OverweightEventListView.as_view(),              name="wb-overweight-events"),
    path("overweight-events/export/csv/",           views.OverweightEventExportCSVView.as_view(),         name="wb-overweight-events-export-csv"),
    path("overweight-config/<int:branch_pk>/",      views.OverweightConfigView.as_view(),                 name="wb-overweight-config"),
    path("camera-configs/",                         views.CameraConfigListCreateView.as_view(),           name="wb-camera-configs"),
    path("camera-configs/preview/",                 views.CameraConfigPreviewView.as_view(),              name="wb-camera-config-preview"),
    path("camera-configs/recognize-plate/",         views.CameraPlateRecognitionView.as_view(),           name="wb-camera-recognize-plate"),
    path("camera-configs/<int:pk>/",                views.CameraConfigDetailView.as_view(),               name="wb-camera-config-detail"),
    path("surveillance-monitor/",                   views.SurveillanceMonitorStatusView.as_view(),        name="wb-surveillance-monitor"),
    path("surveillance-monitor/test/",              views.SurveillanceMonitorTestView.as_view(),          name="wb-surveillance-monitor-test"),
    path("surveillance-discrepancies/check/",       views.CheckDiscrepanciesView.as_view(),               name="wb-discrepancies-check"),
    path("surveillance-discrepancies/",             views.WeighbridgeDiscrepancyListView.as_view(),       name="wb-discrepancies"),
    path("surveillance-discrepancies/<int:pk>/",    views.WeighbridgeDiscrepancyDetailView.as_view(),     name="wb-discrepancy-detail"),
]
