# Generated by Django 5.2.16 on 2026-07-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Procurement', '0002_bill'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bill',
            name='bill_unique_number_per_tenant',
        ),
        migrations.AlterField(
            model_name='bill',
            name='reference',
            field=models.CharField(blank=True, help_text="Supplier's own reference number", max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Fallback if no FK supplier', max_length=200),
        ),
    ]
