# Generated by Django 5.2.16 on 2026-07-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Platform_Core", "0011_accounting_periods"),
        ("SL_Procurement", "0003_remove_bill_bill_unique_number_per_tenant_and_more"),
        ("SL_Weighbridge", "0055_backfill_customer_vehicle_tenants"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requisition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_number", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("cost_center", models.CharField(max_length=120)),
                ("project_code", models.CharField(blank=True, max_length=80)),
                ("needed_by", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted"), ("pending_approval", "Pending Approval"), ("approved", "Approved"), ("rejected", "Rejected"), ("cancelled", "Cancelled"), ("po_created", "PO Created")], default="draft", max_length=20)),
                ("budget_status", models.CharField(choices=[("pending", "Pending"), ("passed", "Passed"), ("warning", "Warning"), ("blocked", "Blocked")], default="pending", max_length=20)),
                ("budget_message", models.CharField(blank=True, max_length=255)),
                ("estimated_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(default="KES", max_length=10)),
                ("vendor_option", models.CharField(blank=True, max_length=200)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requisitions", to="SL_Weighbridge.branch")),
                ("gl_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requisitions", to="Platform_Core.account")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requisitions", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requisitions", to="Platform_Core.tenant")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequisitionLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_type", models.CharField(choices=[("goods", "Goods"), ("service", "Service")], default="goods", max_length=20)),
                ("description", models.CharField(max_length=300)),
                ("unit", models.CharField(default="pcs", max_length=50)),
                ("quantity", models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("gl_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requisition_lines", to="Platform_Core.account")),
                ("requisition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="SL_Procurement.requisition")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]

