# Generated by Django 5.2.16 on 2026-07-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Platform_Core", "0011_accounting_periods"),
        ("SL_Procurement", "0004_requisition_requisitionline"),
        ("SL_Weighbridge", "0055_backfill_customer_vehicle_tenants"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="branch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="purchase_orders", to="SL_Weighbridge.branch"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="cost_center",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="gl_account",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="purchase_orders", to="Platform_Core.account"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="project_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="requisition",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="purchase_orders", to="SL_Procurement.requisition"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tenant",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="purchase_orders", to="Platform_Core.tenant"),
        ),
    ]

