# Generated by Django 5.2.16 on 2026-07-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("SL_Procurement", "0005_purchaseorder_workflow_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalMatrix",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("cost_center", models.CharField(blank=True, max_length=120)),
                ("min_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("max_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("step_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approval_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="procurement_approval_rules", to="auth.group")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approval_matrices", to="Platform_Core.tenant")),
            ],
            options={
                "ordering": ["tenant__name", "step_order", "min_amount"],
            },
        ),
        migrations.CreateModel(
            name="RequisitionApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_order", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("skipped", "Skipped")], default="pending", max_length=20)),
                ("decision_notes", models.TextField(blank=True)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="acted_procurement_approvals", to=settings.AUTH_USER_MODEL)),
                ("approval_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="procurement_approvals", to="auth.group")),
                ("assigned_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_procurement_approvals", to=settings.AUTH_USER_MODEL)),
                ("matrix", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approval_steps", to="SL_Procurement.approvalmatrix")),
                ("requisition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="SL_Procurement.requisition")),
            ],
            options={
                "ordering": ["step_order", "id"],
            },
        ),
    ]

