# Generated by Django 5.2.16 on 2026-07-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("SL_Procurement", "0006_approvalmatrix_requisitionapproval"),
        ("SL_Weighbridge", "0055_backfill_customer_vehicle_tenants"),
        ("Platform_Core", "0015_workflow_center_menu"),
        ("SL_CRM", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceiptNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("received_date", models.DateField(default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("received", "Received"), ("partial", "Partial"), ("closed", "Closed")], default="draft", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="goods_receipts", to="SL_Weighbridge.branch")),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="goods_receipts", to="SL_Procurement.purchaseorder")),
                ("received_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="goods_receipts", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="goods_receipts", to="Platform_Core.tenant")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="GoodsReceiptLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=300)),
                ("ordered_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ("received_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ("accepted_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("goods_receipt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="SL_Procurement.goodsreceiptnote")),
                ("purchase_order_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="receipt_lines", to="SL_Procurement.purchaseorderitem")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="bill",
            name="goods_receipt",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bills", to="SL_Procurement.goodsreceiptnote"),
        ),
        migrations.AddField(
            model_name="bill",
            name="match_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="bill",
            name="purchase_order",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bills", to="SL_Procurement.purchaseorder"),
        ),
        migrations.CreateModel(
            name="MatchException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exception_type", models.CharField(choices=[("missing_po", "Missing PO"), ("missing_receipt", "Missing Receipt"), ("quantity_variance", "Quantity Variance"), ("price_variance", "Price Variance"), ("line_missing", "Line Missing")], max_length=30)),
                ("status", models.CharField(choices=[("open", "Open"), ("resolved", "Resolved"), ("waived", "Waived")], default="open", max_length=20)),
                ("line_reference", models.CharField(blank=True, max_length=255)),
                ("variance_percent", models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ("message", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bill", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="match_exceptions", to="SL_Procurement.bill")),
                ("goods_receipt", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="match_exceptions", to="SL_Procurement.goodsreceiptnote")),
                ("purchase_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="match_exceptions", to="SL_Procurement.purchaseorder")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="match_exceptions", to="Platform_Core.tenant")),
            ],
            options={"ordering": ["status", "-created_at"]},
        ),
    ]
