# Generated by Django 5.2.16 on 2026-07-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("SL_Procurement", "0007_goodsreceiptnote_goodsreceiptline_matchexception_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentQueueItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("supplier_name", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("ready", "Ready"), ("scheduled", "Scheduled"), ("paid", "Paid"), ("blocked", "Blocked")], default="pending", max_length=20)),
                ("payment_reference", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_queue_items", to="SL_Procurement.bill")),
                ("prepared_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="prepared_payment_queue_items", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_queue_items", to="Platform_Core.tenant")),
            ],
            options={"ordering": ["status", "due_date", "-created_at"]},
        ),
    ]

