# Generated by Django 5.2.16 on 2026-07-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform_Core', '0006_tenant_user_profile_branch_settings'),
        ('SL_Sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='estimate',
            name='estimate_unique_number_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='product_unique_code_per_tenant',
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage, e.g. 16 for 16%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g. kg, ton, unit, hour', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('tenant', 'estimate_number')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'code')},
        ),
    ]
