# Generated by Django 5.2.16 on 2026-07-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("Platform_Core", "0013_procurement_approval_rules_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=180)),
                ("entity_type", models.CharField(max_length=100)),
                ("scope", models.CharField(choices=[("document", "Document"), ("transaction", "Transaction"), ("master_data", "Master Data"), ("custom", "Custom")], default="document", max_length=20)),
                ("trigger_event", models.CharField(default="submit", max_length=80)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_dashboard_quick_actions", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("module", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workflow_definitions", to="Platform_Core.moduledefinition")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workflow_definitions", to="Platform_Core.tenant")),
            ],
            options={
                "ordering": ["tenant__name", "name"],
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowStepDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("step_order", models.PositiveIntegerField(default=1)),
                ("action_type", models.CharField(choices=[("approval", "Approval"), ("review", "Review"), ("notify", "Notify")], default="approval", max_length=20)),
                ("min_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("max_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("cost_center", models.CharField(blank=True, max_length=120)),
                ("notify_dashboard", models.BooleanField(default=True)),
                ("allow_quick_action", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("approval_group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="workflow_step_definitions", to="auth.group")),
                ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="Platform_Core.workflowdefinition")),
            ],
            options={
                "ordering": ["workflow__name", "step_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowInboxItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module_slug", models.CharField(blank=True, max_length=100)),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.PositiveIntegerField()),
                ("reference", models.CharField(blank=True, max_length=80)),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True)),
                ("route_path", models.CharField(blank=True, max_length=255)),
                ("action_url", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("cancelled", "Cancelled"), ("completed", "Completed")], default="pending", max_length=20)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("quick_actions", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("acted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workflow_inbox_acted", to=settings.AUTH_USER_MODEL)),
                ("assigned_group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workflow_inbox_items", to="auth.group")),
                ("assigned_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workflow_inbox_assigned", to=settings.AUTH_USER_MODEL)),
                ("step_definition", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inbox_items", to="Platform_Core.workflowstepdefinition")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workflow_inbox_items", to="Platform_Core.tenant")),
                ("workflow", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inbox_items", to="Platform_Core.workflowdefinition")),
            ],
            options={
                "ordering": ["status", "-created_at"],
            },
        ),
    ]

