# Generated by Django 4.2.15 on 2024-09-01 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gross_weight',
            field=models.DecimalField(decimal_places=2, default='18000', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operator',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tare_weight',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vehicle',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vehicle_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.vehicletype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='weight_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='weight_type',
            field=models.CharField(choices=[('First Weight', 'First Weight'), ('Second Weight', 'Second Weight')], max_length=20),
        ),
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=100)),
                ('connection_type', models.CharField(choices=[('USB', 'USB'), ('Ethernet', 'Ethernet'), ('Serial', 'Serial')], max_length=20)),
                ('port', models.CharField(max_length=100)),
                ('baud_rate', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.branch')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=100)),
                ('connection_type', models.CharField(choices=[('USB', 'USB'), ('Ethernet', 'Ethernet'), ('Serial', 'Serial')], max_length=20)),
                ('port', models.CharField(max_length=100)),
                ('baud_rate', models.IntegerField()),
                ('data_bits', models.IntegerField()),
                ('parity', models.CharField(max_length=10)),
                ('stop_bits', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.company'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.branch'),
            preserve_default=False,
        ),
    ]
