# Generated by Django 4.2.15 on 2024-09-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0002_branch_company_remove_transaction_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='manual_weight_capture',
            field=models.BooleanField(default=False),
        ),
    ]
