# Generated by Django 4.2.15 on 2024-09-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0003_transaction_manual_weight_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gross_weight_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tare_weight_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
