# Generated by Django 4.1.2 on 2024-09-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0004_transaction_gross_weight_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorconfig',
            name='baud_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorconfig',
            name='data_bits',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='indicatorconfig',
            name='parity',
            field=models.CharField(choices=[('None', 'None'), ('Even', 'Even'), ('Odd', 'Odd')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='indicatorconfig',
            name='port',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorconfig',
            name='stop_bits',
            field=models.IntegerField(default=1),
        ),
    ]
