# Generated by Django 4.1.2 on 2024-09-03 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0005_alter_indicatorconfig_baud_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='config_files/')),
            ],
        ),
        migrations.CreateModel(
            name='DiscrepancyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='discrepancy_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='indicatorconfig',
            name='command_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.configurationfile'),
        ),
        migrations.AddField(
            model_name='printerconfig',
            name='command_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.configurationfile'),
        ),
    ]
