# Generated by Django 4.1.2 on 2024-09-03 21:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0006_configurationfile_discrepancyreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerconfig',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='printerconfig',
            name='printer_name',
        ),
        migrations.AddField(
            model_name='printerconfig',
            name='data_bits',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='printerconfig',
            name='parity',
            field=models.CharField(choices=[('None', 'None'), ('Even', 'Even'), ('Odd', 'Odd')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='printerconfig',
            name='stop_bits',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='baud_rate',
            field=models.IntegerField(default=9600, validators=[django.core.validators.MinValueValidator(9600), django.core.validators.MaxValueValidator(115200)]),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_configs', to='SL_Weighbridge.branch'),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='command_file',
            field=models.FileField(blank=True, null=True, upload_to='printer_commands/'),
        ),
    ]
