# Generated by Django 4.1.2 on 2024-09-10 00:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0007_remove_printerconfig_connection_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerconfig',
            name='command_file',
        ),
        migrations.AddField(
            model_name='indicatorconfig',
            name='mode',
            field=models.IntegerField(choices=[(0, 'No Transmission'), (1, 'Continuous Transmission'), (2, 'Transmission if No-Motion'), (3, 'On Demand Transmission')], default=1),
        ),
        migrations.AddField(
            model_name='indicatorconfig',
            name='node_number',
            field=models.IntegerField(default=49, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='printerconfig',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printerconfig',
            name='name',
            field=models.CharField(default='Unknown Printer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printerconfig',
            name='printer_type',
            field=models.CharField(choices=[('Zebra', 'Zebra'), ('Epson', 'Epson')], default='Unknown Printer', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.vehicletype'),
        ),
    ]
