# Generated by Django 4.1.2 on 2024-09-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0008_remove_printerconfig_command_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gross_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='net_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tare_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
