# Generated by Django 4.1.2 on 2024-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0009_alter_transaction_gross_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('IP', 'IP'), ('Cable', 'Cable'), ('Other', 'Other')], max_length=10)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('other_parameters', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehiclepresence',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehiclepresence',
            name='detected_weight',
            field=models.FloatField(),
        ),
    ]
