# Generated by Django 4.1.2 on 2024-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0010_cameraconfig_vehiclepresence_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraconfig',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cameraconfig',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
