# Generated by Django 4.1.2 on 2024-09-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0011_cameraconfig_password_cameraconfig_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['number_plate']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.branch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gross_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='net_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tare_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
