# Generated by Django 4.1.2 on 2024-09-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0012_alter_customer_options_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.vehicletype'),
            preserve_default=False,
        ),
    ]
