# Generated by Django 4.1.2 on 2024-09-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0013_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
