# Generated by Django 4.2.16 on 2024-10-08 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0017_alter_transaction_options_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discrepancyreport',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='discrepancyreport',
            name='report_file',
        ),
        migrations.AddField(
            model_name='discrepancyreport',
            name='detected_weight',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discrepancyreport',
            name='image',
            field=models.ImageField(default=1, upload_to='discrepancy_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discrepancyreport',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclepresence',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
