# Generated by Django 4.2.16 on 2024-10-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0018_remove_discrepancyreport_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa - Direct'), ('Bank Deposit', 'Bank Deposit'), ('Debt', 'Debt')], default='Cash', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Invoiced', 'Invoiced')], default='Paid', max_length=20),
            preserve_default=False,
        ),
    ]
