# Generated by Django 4.2.16 on 2024-10-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0019_transaction_invoiced_transaction_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
