# Generated by Django 4.2.16 on 2024-10-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0020_transaction_paired_alter_transaction_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.CharField(default='Destination', max_length=100, verbose_name='Destination'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa - Direct'), ('Bank Deposit', 'Bank Deposit'), ('Debt', 'Debt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='weight_type',
            field=models.CharField(blank=True, choices=[('First Weight', 'First Weight'), ('Second Weight', 'Second Weight')], max_length=20),
        ),
    ]
