# Generated by Django 4.2.16 on 2024-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0021_transaction_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa - Direct'), ('Bank Deposit', 'Bank Deposit'), ('Debt', 'Debt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='weight_type',
            field=models.CharField(choices=[('First Weight', 'First Weight'), ('Second Weight', 'Second Weight')], max_length=20),
        ),
    ]
