# Generated by Django 4.2.16 on 2024-10-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0022_alter_transaction_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='weight_type',
            field=models.CharField(blank=True, choices=[('First Weight', 'First Weight'), ('Second Weight', 'Second Weight')], max_length=20),
        ),
    ]
