# Generated by Django 4.2.16 on 2024-10-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0023_alter_transaction_weight_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='weight_type',
            field=models.CharField(choices=[('Select', 'Select'), ('First Weight', 'First Weight'), ('Second Weight', 'Second Weight')], default='Select', max_length=20),
        ),
    ]
