# Generated by Django 4.2.16 on 2024-10-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0024_alter_transaction_weight_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='weight_type',
            field=models.CharField(choices=[('First Weight', 'First Weight'), ('Second Weight', 'Second Weight')], max_length=20),
        ),
    ]
