# Generated by Django 4.2.16 on 2024-10-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SL_Weighbridge', '0025_alter_transaction_weight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('is_approval_step', models.BooleanField(default=False)),
                ('groups_allowed', models.ManyToManyField(blank=True, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='workflow_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SL_Weighbridge.workflowstep'),
        ),
    ]
