# Generated by Django 4.2.16 on 2024-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0026_transaction_approval_status_workflowstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='manual_receipt',
            field=models.FileField(blank=True, null=True, upload_to='manual_receipts/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='weight_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
