# Generated by Django 4.2.16 on 2024-10-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0027_transaction_manual_receipt_transaction_weight_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('can_export_csv', 'Can export transactions to CSV'), ('can_approve_pending_transactions', 'Can approve pending transactions')]},
        ),
    ]
