# Generated by Django 4.2.16 on 2024-10-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0028_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('can_export_csv', 'Can export transactions to CSV'), ('can_approve_transaction', 'Can approve pending transactions')]},
        ),
    ]
