# Generated by Django 4.2.16 on 2024-11-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0031_customer_charge_customer_discounted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVehicleTypeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.customer')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SL_Weighbridge.vehicletype')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='vehicle_type_discounts',
            field=models.ManyToManyField(blank=True, related_name='discounted_customers', through='SL_Weighbridge.CustomerVehicleTypeDiscount', to='SL_Weighbridge.vehicletype'),
        ),
    ]
