# Generated by Django 4.2.16 on 2024-11-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0034_invoice_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='transaction',
        ),
        migrations.AddField(
            model_name='invoice',
            name='transactions',
            field=models.ManyToManyField(to='SL_Weighbridge.transaction'),
        ),
    ]
