# Generated by Django 4.2.16 on 2024-12-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0035_remove_invoice_transaction_invoice_transactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('can_export_transaction', 'Can export transactions to CSV'), ('can_approve_pending_transactions', 'Can pending completed transactions'), ('can_recall_completed_transactions', 'Can recall completed transactions')]},
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='max_gross_weight',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum gross weight in KG for this vehicle type.', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(choices=[('', 'Select Payment Mode'), ('Cash', 'Cash'), ('Mpesa', 'Mpesa - Direct'), ('Bank Deposit', 'Bank Deposit'), ('Debt', 'Debt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('', 'Select Payment Status'), ('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='weight_type',
            field=models.CharField(choices=[('', 'Select Payment Status'), ('First Weight', 'First Weight'), ('Second Weight', 'Second Weight')], max_length=20),
        ),
    ]
