# Generated by Django 4.2.16 on 2025-05-26 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0036_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paired_first_transaction',
            field=models.ForeignKey(blank=True, limit_choices_to={'weight_type': 'First Weight'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_second_transactions', to='SL_Weighbridge.transaction'),
        ),
    ]
