# Generated by Django 4.2.16 on 2025-06-15 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0038_alter_invoice_total_amount_invoiceline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issued_date']},
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='max_tare_weight',
            field=models.PositiveIntegerField(help_text='Maximum tare weight in KG for this vehicle type.', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 7, 1, 42, 783609, tzinfo=datetime.timezone.utc)),
        ),
    ]
