# Generated by Django 4.2.16 on 2025-07-16 19:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SL_Weighbridge', '0039_alter_invoice_options_vehicletype_max_tare_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 15, 19, 41, 16, 428311, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('transactions', 'Transaction Report'), ('vehicles', 'Vehicle Presence Report'), ('invoices', 'Invoice Report')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_reports/')),
                ('filters_applied', models.TextField(blank=True, help_text='JSON or description of filters used')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
