# Generated by Django 5.2.16 on 2026-07-16 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0040_alter_invoice_due_date_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 15, 10, 29, 48, 524325, tzinfo=datetime.timezone.utc)),
        ),
    ]
