# Generated by Django 5.2.16 on 2026-07-16 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0041_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 15, 11, 31, 10, 925253, tzinfo=datetime.timezone.utc)),
        ),
    ]
