# Generated by Django 5.2.16 on 2026-07-16 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0042_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorconfig',
            name='live_weight_url',
            field=models.CharField(blank=True, help_text='URL that returns {value, stable, timestamp} — polled for live display. e.g. https://ws.metrixws.co.ke/live_weight', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indicatorconfig',
            name='max_first_weight_age_days',
            field=models.IntegerField(default=333, help_text='How many days back to look for a matching pending First Weight when capturing Second Weight. Default 333.'),
        ),
        migrations.AddField(
            model_name='indicatorconfig',
            name='stable_weight_url',
            field=models.CharField(blank=True, help_text='URL that returns a stable/confirmed reading. Falls back to live_weight_url if blank.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorconfig',
            name='connection_type',
            field=models.CharField(choices=[('USB', 'USB'), ('Ethernet', 'Ethernet'), ('Serial', 'Serial'), ('HTTP', 'HTTP / REST API')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 15, 11, 35, 49, 449925, tzinfo=datetime.timezone.utc)),
        ),
    ]
