# Generated by Django 5.2.16 on 2026-07-16 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0043_indicator_http_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 15, 11, 40, 11, 790507, tzinfo=datetime.timezone.utc)),
        ),
    ]
