# Generated by Django 5.2.16 on 2026-07-16 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0044_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorconfig',
            name='max_first_weight_age_days',
            field=models.IntegerField(default=3, help_text='How many days back to look for a matching pending First Weight when capturing Second Weight. Default 3.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 15, 12, 29, 0, 202609, tzinfo=datetime.timezone.utc)),
        ),
    ]
