# Generated by Django 5.2.16 on 2026-07-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform_Core', '0006_tenant_user_profile_branch_settings'),
        ('SL_Weighbridge', '0048_invoiceemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='Platform_Core.tenant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighbridge_transactions', to='Platform_Core.tenant'),
        ),
    ]
