# Generated by Django 5.2.16 on 2026-07-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0050_overweight_surveillance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overweightconfig',
            name='grace_window_minutes',
            field=models.IntegerField(default=30, help_text='Minutes after an OverweightEvent before it is promoted to a discrepancy if no matching transaction is found.'),
        ),
        migrations.AlterField(
            model_name='overweightconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='overweightconfig',
            name='surveillance_enabled',
            field=models.BooleanField(default=True, help_text='Master switch — disabling this stops all overweight event creation for this branch.'),
        ),
        migrations.AlterField(
            model_name='overweightconfig',
            name='threshold_kg',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Net weight (kg) at or above which an OverweightEvent is created.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='overweightevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='overweightevent',
            name='net_weight',
            field=models.IntegerField(help_text='The weight value that triggered this event.'),
        ),
        migrations.AlterField(
            model_name='overweightevent',
            name='threshold_at_capture',
            field=models.IntegerField(help_text='Branch threshold (kg) in force when this event was created.'),
        ),
        migrations.AlterField(
            model_name='overweightevent',
            name='vehicle_plate',
            field=models.CharField(blank=True, default='', help_text='Number plate at the time of capture (may be blank if no transaction was open).', max_length=20),
        ),
        migrations.AlterField(
            model_name='weighbridgediscrepancy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
