# Generated by Django 5.2.16 on 2026-07-26 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform_Core', '0009_industries_pricing_rules'),
        ('SL_Weighbridge', '0053_vehicletype_linked_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighbridge_customers', to='Platform_Core.tenant'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighbridge_vehicles', to='Platform_Core.tenant'),
        ),
        migrations.CreateModel(
            name='WeighingOperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('flow_kind', models.CharField(choices=[('first', 'First Weight'), ('second', 'Second Weight'), ('single', 'Single Weight'), ('axle', 'Axle Weight')], default='first', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=10)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weighing_operation_types', to='Platform_Core.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='operation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='SL_Weighbridge.weighingoperationtype'),
        ),
    ]
