# Generated by Codex on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0063_transaction_driver_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
