# Generated by Codex on 2026-08-13

from django.db import migrations, models
import django.db.models.deletion


def backfill_company_and_branch_tenants(apps, schema_editor):
    Tenant = apps.get_model("Platform_Core", "Tenant")
    Company = apps.get_model("SL_Weighbridge", "Company")
    Branch = apps.get_model("SL_Weighbridge", "Branch")

    tenant_by_name = {}
    for tenant in Tenant.objects.all().order_by("id"):
        tenant_by_name.setdefault((tenant.name or "").strip().lower(), []).append(tenant.id)
        legal_name = (getattr(tenant, "legal_name", "") or "").strip().lower()
        if legal_name:
            tenant_by_name.setdefault(legal_name, []).append(tenant.id)

    for company in Company.objects.filter(tenant__isnull=True).order_by("id"):
        matches = tenant_by_name.get((company.name or "").strip().lower(), [])
        if len(matches) == 1:
            company.tenant_id = matches[0]
            company.save(update_fields=["tenant"])

    for branch in Branch.objects.filter(tenant__isnull=True).select_related("company").order_by("id"):
        company_tenant_id = getattr(branch.company, "tenant_id", None)
        if company_tenant_id:
            branch.tenant_id = company_tenant_id
            branch.save(update_fields=["tenant"])


class Migration(migrations.Migration):

    dependencies = [
        ("Platform_Core", "0028_organization_membership"),
        ("SL_Weighbridge", "0065_customer_lifecycle_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weighbridge_companies",
                to="Platform_Core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weighbridge_branches",
                to="Platform_Core.tenant",
            ),
        ),
        migrations.RunPython(backfill_company_and_branch_tenants, migrations.RunPython.noop),
    ]
