# Generated by Codex on 2026-08-13

from collections import defaultdict

from django.db import migrations, models
import django.db.models.deletion


def backfill_reference_tenants(apps, schema_editor):
    VehicleType = apps.get_model("SL_Weighbridge", "VehicleType")
    Item = apps.get_model("SL_Weighbridge", "Item")
    Currency = apps.get_model("SL_Weighbridge", "Currency")
    Transaction = apps.get_model("SL_Weighbridge", "Transaction")
    Vehicle = apps.get_model("SL_Weighbridge", "Vehicle")
    CustomerVehicleTypeDiscount = apps.get_model("SL_Weighbridge", "CustomerVehicleTypeDiscount")

    vehicle_type_tenants = defaultdict(set)
    item_tenants = defaultdict(set)
    currency_tenants = defaultdict(set)

    for row in Transaction.objects.exclude(tenant=None).values("tenant_id", "vehicle_type_id", "item_id"):
        tenant_id = row["tenant_id"]
        if tenant_id and row["vehicle_type_id"]:
            vehicle_type_tenants[row["vehicle_type_id"]].add(tenant_id)
        if tenant_id and row["item_id"]:
            item_tenants[row["item_id"]].add(tenant_id)

    for row in Vehicle.objects.exclude(tenant=None).values("tenant_id", "vehicle_type_id"):
        tenant_id = row["tenant_id"]
        if tenant_id and row["vehicle_type_id"]:
            vehicle_type_tenants[row["vehicle_type_id"]].add(tenant_id)

    for row in CustomerVehicleTypeDiscount.objects.select_related("customer").exclude(
        customer__tenant=None
    ).values("customer__tenant_id", "vehicle_type_id"):
        tenant_id = row["customer__tenant_id"]
        if tenant_id and row["vehicle_type_id"]:
            vehicle_type_tenants[row["vehicle_type_id"]].add(tenant_id)

    for vehicle_type in VehicleType.objects.filter(tenant__isnull=True).order_by("id"):
        tenant_ids = vehicle_type_tenants.get(vehicle_type.id, set())
        if len(tenant_ids) == 1:
            vehicle_type.tenant_id = next(iter(tenant_ids))
            vehicle_type.save(update_fields=["tenant"])
            if vehicle_type.currency_id:
                currency_tenants[vehicle_type.currency_id].add(vehicle_type.tenant_id)

    for item in Item.objects.filter(tenant__isnull=True).order_by("id"):
        tenant_ids = item_tenants.get(item.id, set())
        if len(tenant_ids) == 1:
            item.tenant_id = next(iter(tenant_ids))
            item.save(update_fields=["tenant"])
            if item.currency_id:
                currency_tenants[item.currency_id].add(item.tenant_id)

    for currency in Currency.objects.filter(tenant__isnull=True).order_by("id"):
        tenant_ids = set(currency_tenants.get(currency.id, set()))
        if not tenant_ids:
            tenant_ids.update(
                VehicleType.objects.filter(currency_id=currency.id, tenant__isnull=False).values_list("tenant_id", flat=True)
            )
            tenant_ids.update(
                Item.objects.filter(currency_id=currency.id, tenant__isnull=False).values_list("tenant_id", flat=True)
            )
        tenant_ids = {tenant_id for tenant_id in tenant_ids if tenant_id}
        if len(tenant_ids) == 1:
            currency.tenant_id = next(iter(tenant_ids))
            currency.save(update_fields=["tenant"])


class Migration(migrations.Migration):

    dependencies = [
        ("Platform_Core", "0028_organization_membership"),
        ("SL_Weighbridge", "0066_company_branch_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weighbridge_currencies",
                to="Platform_Core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weighbridge_items",
                to="Platform_Core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weighbridge_vehicle_types",
                to="Platform_Core.tenant",
            ),
        ),
        migrations.RunPython(backfill_reference_tenants, migrations.RunPython.noop),
    ]
