# Generated by Django 6.0.7 on 2026-09-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SL_Weighbridge', '0072_alter_branch_phone_alter_company_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'permissions': [('can_view_customer_statements', 'Can view customer statements')]},
        ),
    ]
