from django.urls import path

from .views import (
    AuditAccessLogListAPIView,
    AuditEventLogListAPIView,
    AuthStatusAPIView,
    BackupPolicyDetailAPIView,
    BackupPolicyListCreateAPIView,
    BackupPolicyDownloadAPIView,
    BackupPolicyRunAPIView,
    ChangePasswordAPIView,
    CurrentUserAPIView,
    DocumentTemplateDetailAPIView,
    DocumentTemplateListCreateAPIView,
    DocumentTemplatePreviewAPIView,
    ForgotPasswordAPIView,
    IndustryDetailAPIView,
    IndustryListCreateAPIView,
    IntegrationEndpointDetailAPIView,
    IntegrationEndpointListCreateAPIView,
    LicenseKeyDetailAPIView,
    LicenseKeyListCreateAPIView,
    ModuleDefinitionDetailAPIView,
    ModuleDefinitionListCreateAPIView,
    PlanModuleDetailAPIView,
    PlanModuleListCreateAPIView,
    PlatformPermissionListAPIView,
    PlatformRoleDetailAPIView,
    PlatformRoleListAPIView,
    PlatformUserDetailAPIView,
    PlatformUserListAPIView,
    PlatformUserUpdateAPIView,
    PlatformUserMembershipDetailAPIView,
    PlatformUserMembershipListCreateAPIView,
    PricingRuleDetailAPIView,
    PricingRuleListCreateAPIView,
    PricingRuleTypeDetailAPIView,
    PricingRuleTypeListCreateAPIView,
    RecordAuditTrailAPIView,
    SubscriptionPlanDetailAPIView,
    SubscriptionPlanListCreateAPIView,
    SubscriptionBillingRequestDetailAPIView,
    SubscriptionBillingRequestSimulateCancelAPIView,
    SubscriptionBillingRequestListCreateAPIView,
    SubscriptionBillingRequestSimulateCompleteAPIView,
    SubscriptionBillingRequestSimulateFailAPIView,
    SubscriptionBillingSummaryAPIView,
    SwitchOrganizationAPIView,
    TenantBranchDetailAPIView,
    TenantBranchListCreateAPIView,
    TenantDetailAPIView,
    TenantListCreateAPIView,
    TenantModuleActivationDetailAPIView,
    TenantModuleActivationListCreateAPIView,
    TenantOffboardingExportAPIView,
    TenantOffboardingRequestDeleteAPIView,
    TenantOffboardingStatusAPIView,
    TenantSettingsAPIView,
    TenantSubscriptionDetailAPIView,
    TenantSelfAPIView,
    TenantSubscriptionListCreateAPIView,
    TenantUserInviteAPIView,
    TenantUserListAPIView,
    TokenLoginAPIView,
    TokenLogoutAPIView,
    PublicRegistrationAPIView,
    WorkspaceNavigationAPIView,
    WorkspaceMenuItemDetailAPIView,
    WorkspaceMenuItemListCreateAPIView,
    WorkspaceMenuSectionDetailAPIView,
    WorkspaceMenuSectionListCreateAPIView,
    WorkspaceRoleMenuAccessDetailAPIView,
    WorkspaceRoleMenuAccessListCreateAPIView,
    WorkflowDefinitionDetailAPIView,
    WorkflowDefinitionListCreateAPIView,
    WorkflowEntityBindingDetailAPIView,
    WorkflowEntityBindingListCreateAPIView,
    WorkflowInboxAPIView,
    WorkflowNodeDefinitionDetailAPIView,
    WorkflowNodeDefinitionListCreateAPIView,
    WorkflowStepDefinitionDetailAPIView,
    WorkflowStepDefinitionListCreateAPIView,
    WorkflowTransitionDefinitionDetailAPIView,
    WorkflowTransitionDefinitionListCreateAPIView,
    PlatformUserRoleAssignmentAPIView,
    PublicSiteConfigurationAPIView,
    activate_license_action,
    activate_tenant,
    generate_license_action,
    indicator_source_registry_overview,
    integration_health_overview,
    platform_overview,
    provision_tenant,
    revoke_license_action,
    subscription_sync_modules_action,
    suspend_tenant,
    tenant_module_access_overview,
    test_tenant_smtp,
    validate_license_action,
)


urlpatterns = [
    path("", platform_overview, name="platform-module-overview"),
    # Auth
    path("auth/status/", AuthStatusAPIView.as_view(), name="platform-auth-status"),
    path("public/site/", PublicSiteConfigurationAPIView.as_view(), name="platform-public-site"),
    path("auth/register/", PublicRegistrationAPIView.as_view(), name="platform-auth-register"),
    path("auth/token/", TokenLoginAPIView.as_view(), name="platform-auth-token"),
    path("auth/forgot-password/", ForgotPasswordAPIView.as_view(), name="platform-auth-forgot-password"),
    path("auth/me/", CurrentUserAPIView.as_view(), name="platform-auth-me"),
    path("auth/change-password/", ChangePasswordAPIView.as_view(), name="platform-auth-change-password"),
    path("auth/switch-organization/", SwitchOrganizationAPIView.as_view(), name="platform-auth-switch-organization"),
    path("auth/logout/", TokenLogoutAPIView.as_view(), name="platform-auth-logout"),
    # Workspace / nav
    path("workspace/navigation/", WorkspaceNavigationAPIView.as_view(), name="platform-workspace-navigation"),
    path("workspace/menu-sections/", WorkspaceMenuSectionListCreateAPIView.as_view(), name="workspace-menu-section-list"),
    path("workspace/menu-sections/<int:pk>/", WorkspaceMenuSectionDetailAPIView.as_view(), name="workspace-menu-section-detail"),
    path("workspace/menu-items/", WorkspaceMenuItemListCreateAPIView.as_view(), name="workspace-menu-item-list"),
    path("workspace/menu-items/<int:pk>/", WorkspaceMenuItemDetailAPIView.as_view(), name="workspace-menu-item-detail"),
    path("workspace/menu-access/", WorkspaceRoleMenuAccessListCreateAPIView.as_view(), name="workspace-menu-access-list"),
    path("workspace/menu-access/<int:pk>/", WorkspaceRoleMenuAccessDetailAPIView.as_view(), name="workspace-menu-access-detail"),
    path("workflows/definitions/", WorkflowDefinitionListCreateAPIView.as_view(), name="workflow-definition-list"),
    path("workflows/definitions/<int:pk>/", WorkflowDefinitionDetailAPIView.as_view(), name="workflow-definition-detail"),
    path("workflows/entity-bindings/", WorkflowEntityBindingListCreateAPIView.as_view(), name="workflow-entity-binding-list"),
    path("workflows/entity-bindings/<int:pk>/", WorkflowEntityBindingDetailAPIView.as_view(), name="workflow-entity-binding-detail"),
    path("workflows/steps/", WorkflowStepDefinitionListCreateAPIView.as_view(), name="workflow-step-list"),
    path("workflows/steps/<int:pk>/", WorkflowStepDefinitionDetailAPIView.as_view(), name="workflow-step-detail"),
    path("workflows/nodes/", WorkflowNodeDefinitionListCreateAPIView.as_view(), name="workflow-node-list"),
    path("workflows/nodes/<int:pk>/", WorkflowNodeDefinitionDetailAPIView.as_view(), name="workflow-node-detail"),
    path("workflows/transitions/", WorkflowTransitionDefinitionListCreateAPIView.as_view(), name="workflow-transition-list"),
    path("workflows/transitions/<int:pk>/", WorkflowTransitionDefinitionDetailAPIView.as_view(), name="workflow-transition-detail"),
    path("workflows/inbox/", WorkflowInboxAPIView.as_view(), name="workflow-inbox"),
    # Users & roles
    path("users/", PlatformUserListAPIView.as_view(), name="platform-user-list"),
    path("users/<int:pk>/", PlatformUserDetailAPIView.as_view(), name="platform-user-detail"),
    path("users/<int:pk>/update/", PlatformUserUpdateAPIView.as_view(), name="platform-user-update"),
    path("users/<int:pk>/memberships/", PlatformUserMembershipListCreateAPIView.as_view(), name="platform-user-membership-list"),
    path("memberships/<int:pk>/", PlatformUserMembershipDetailAPIView.as_view(), name="platform-user-membership-detail"),
    path("users/<int:pk>/assign-roles/", PlatformUserRoleAssignmentAPIView.as_view(), name="platform-user-assign-roles"),
    path("roles/", PlatformRoleListAPIView.as_view(), name="platform-role-list"),
    path("roles/<int:pk>/", PlatformRoleDetailAPIView.as_view(), name="platform-role-detail"),
    path("permissions/", PlatformPermissionListAPIView.as_view(), name="platform-permission-list"),
    path("audit/events/", AuditEventLogListAPIView.as_view(), name="platform-audit-event-list"),
    path("audit/access/", AuditAccessLogListAPIView.as_view(), name="platform-audit-access-list"),
    path("audit/record-trail/", RecordAuditTrailAPIView.as_view(), name="platform-record-audit-trail"),
    # Tenants
    path("tenants/", TenantListCreateAPIView.as_view(), name="tenant-list"),
    path("tenants/self/", TenantSelfAPIView.as_view(), name="tenant-self"),
    path("tenants/provision/", provision_tenant, name="tenant-provision"),
    path("tenants/<int:pk>/", TenantDetailAPIView.as_view(), name="tenant-detail"),
    path("tenants/<int:pk>/suspend/", suspend_tenant, name="tenant-suspend"),
    path("tenants/<int:pk>/activate/", activate_tenant, name="tenant-activate"),
    path("tenants/<int:pk>/offboarding/status/", TenantOffboardingStatusAPIView.as_view(), name="tenant-offboarding-status"),
    path("tenants/<int:pk>/offboarding/export/", TenantOffboardingExportAPIView.as_view(), name="tenant-offboarding-export"),
    path("tenants/<int:pk>/offboarding/request-delete/", TenantOffboardingRequestDeleteAPIView.as_view(), name="tenant-offboarding-request-delete"),
    path("tenants/<int:pk>/branches/", TenantBranchListCreateAPIView.as_view(), name="tenant-branch-list"),
    path("tenants/<int:pk>/users/", TenantUserListAPIView.as_view(), name="tenant-user-list"),
    path("tenants/<int:pk>/users/invite/", TenantUserInviteAPIView.as_view(), name="tenant-user-invite"),
    path("tenants/<int:pk>/settings/", TenantSettingsAPIView.as_view(), name="tenant-settings"),
    path("tenants/<int:pk>/settings/test-smtp/", test_tenant_smtp, name="tenant-settings-test-smtp"),
    path("industries/", IndustryListCreateAPIView.as_view(), name="industry-list"),
    path("industries/<int:pk>/", IndustryDetailAPIView.as_view(), name="industry-detail"),
    # Branches
    path("branches/<int:pk>/", TenantBranchDetailAPIView.as_view(), name="branch-detail"),
    # Modules
    path("modules/", ModuleDefinitionListCreateAPIView.as_view(), name="module-list"),
    path("modules/<int:pk>/", ModuleDefinitionDetailAPIView.as_view(), name="module-detail"),
    path("pricing-rule-types/", PricingRuleTypeListCreateAPIView.as_view(), name="pricing-rule-type-list"),
    path("pricing-rule-types/<int:pk>/", PricingRuleTypeDetailAPIView.as_view(), name="pricing-rule-type-detail"),
    path("pricing-rules/", PricingRuleListCreateAPIView.as_view(), name="pricing-rule-list"),
    path("pricing-rules/<int:pk>/", PricingRuleDetailAPIView.as_view(), name="pricing-rule-detail"),
    # Plans & subscriptions
    path("plans/", SubscriptionPlanListCreateAPIView.as_view(), name="plan-list"),
    path("plans/<int:pk>/", SubscriptionPlanDetailAPIView.as_view(), name="plan-detail"),
    path("plans/<int:plan_pk>/modules/", PlanModuleListCreateAPIView.as_view(), name="plan-module-list"),
    path("plans/<int:plan_pk>/modules/<int:pk>/", PlanModuleDetailAPIView.as_view(), name="plan-module-detail"),
    path("subscriptions/", TenantSubscriptionListCreateAPIView.as_view(), name="subscription-list"),
    path("subscriptions/<int:pk>/", TenantSubscriptionDetailAPIView.as_view(), name="subscription-detail"),
    path("subscriptions/<int:pk>/sync-modules/", subscription_sync_modules_action, name="subscription-sync-modules"),
    path("billing/summary/", SubscriptionBillingSummaryAPIView.as_view(), name="subscription-billing-summary"),
    path("billing/requests/", SubscriptionBillingRequestListCreateAPIView.as_view(), name="subscription-billing-request-list"),
    path("billing/requests/<int:pk>/", SubscriptionBillingRequestDetailAPIView.as_view(), name="subscription-billing-request-detail"),
    path("billing/requests/<int:pk>/simulate-complete/", SubscriptionBillingRequestSimulateCompleteAPIView.as_view(), name="subscription-billing-request-simulate-complete"),
    path("billing/requests/<int:pk>/simulate-fail/", SubscriptionBillingRequestSimulateFailAPIView.as_view(), name="subscription-billing-request-simulate-fail"),
    path("billing/requests/<int:pk>/simulate-cancel/", SubscriptionBillingRequestSimulateCancelAPIView.as_view(), name="subscription-billing-request-simulate-cancel"),
    # Licenses
    path("licenses/generate/", generate_license_action, name="license-generate"),
    path("licenses/", LicenseKeyListCreateAPIView.as_view(), name="license-list"),
    path("licenses/<int:pk>/", LicenseKeyDetailAPIView.as_view(), name="license-detail"),
    path("licenses/<int:pk>/activate/", activate_license_action, name="license-activate"),
    path("licenses/<int:pk>/validate/", validate_license_action, name="license-validate"),
    path("licenses/<int:pk>/revoke/", revoke_license_action, name="license-revoke"),
    # Module activations
    path("module-activations/", TenantModuleActivationListCreateAPIView.as_view(), name="module-activation-list"),
    path("module-activations/<int:pk>/", TenantModuleActivationDetailAPIView.as_view(), name="module-activation-detail"),
    path("module-access/", tenant_module_access_overview, name="tenant-module-access"),
    # Integrations
    path("integrations/", IntegrationEndpointListCreateAPIView.as_view(), name="integration-list"),
    path("integrations/<int:pk>/", IntegrationEndpointDetailAPIView.as_view(), name="integration-detail"),
    path("integrations/health/", integration_health_overview, name="integration-health-overview"),
    path("indicators/source-registry/", indicator_source_registry_overview, name="indicator-source-registry-overview"),
    # Documents & backups
    path("documents/templates/", DocumentTemplateListCreateAPIView.as_view(), name="document-template-list"),
    path("documents/templates/<int:pk>/", DocumentTemplateDetailAPIView.as_view(), name="document-template-detail"),
    path("documents/templates/<int:pk>/preview/", DocumentTemplatePreviewAPIView.as_view(), name="document-template-preview"),
    path("backups/policies/", BackupPolicyListCreateAPIView.as_view(), name="backup-policy-list"),
    path("backups/policies/<int:pk>/", BackupPolicyDetailAPIView.as_view(), name="backup-policy-detail"),
    path("backups/policies/<int:pk>/run/", BackupPolicyRunAPIView.as_view(), name="backup-policy-run"),
    path("backups/policies/<int:pk>/download/", BackupPolicyDownloadAPIView.as_view(), name="backup-policy-download"),
]
