from django.urls import path

from .views import (
    AuthStatusAPIView,
    BackupPolicyDetailAPIView,
    BackupPolicyListCreateAPIView,
    CurrentUserAPIView,
    DocumentTemplateDetailAPIView,
    DocumentTemplateListCreateAPIView,
    IntegrationEndpointDetailAPIView,
    IntegrationEndpointListCreateAPIView,
    LicenseKeyDetailAPIView,
    LicenseKeyListCreateAPIView,
    ModuleDefinitionDetailUpdateAPIView,
    ModuleDefinitionListAPIView,
    PlatformPermissionListAPIView,
    PlatformRoleDetailAPIView,
    PlatformRoleListAPIView,
    PlatformUserDetailAPIView,
    PlatformUserListAPIView,
    PlatformUserUpdateAPIView,
    SubscriptionPlanDetailAPIView,
    SubscriptionPlanListCreateAPIView,
    TenantBranchDetailAPIView,
    TenantBranchListCreateAPIView,
    TenantDetailAPIView,
    TenantListCreateAPIView,
    TenantModuleActivationDetailAPIView,
    TenantModuleActivationListCreateAPIView,
    TenantSettingsAPIView,
    TenantSubscriptionDetailAPIView,
    TenantSelfAPIView,
    TenantSubscriptionListCreateAPIView,
    TenantUserInviteAPIView,
    TenantUserListAPIView,
    TokenLoginAPIView,
    TokenLogoutAPIView,
    WorkspaceNavigationAPIView,
    WorkspaceMenuItemDetailAPIView,
    WorkspaceMenuItemListCreateAPIView,
    WorkspaceMenuSectionDetailAPIView,
    WorkspaceMenuSectionListCreateAPIView,
    WorkspaceRoleMenuAccessDetailAPIView,
    WorkspaceRoleMenuAccessListCreateAPIView,
    PlatformUserRoleAssignmentAPIView,
    activate_license_action,
    activate_tenant,
    indicator_source_registry_overview,
    integration_health_overview,
    platform_overview,
    provision_tenant,
    subscription_sync_modules_action,
    suspend_tenant,
    tenant_module_access_overview,
    test_tenant_smtp,
    validate_license_action,
)


urlpatterns = [
    path("", platform_overview, name="platform-module-overview"),
    # Auth
    path("auth/status/", AuthStatusAPIView.as_view(), name="platform-auth-status"),
    path("auth/token/", TokenLoginAPIView.as_view(), name="platform-auth-token"),
    path("auth/me/", CurrentUserAPIView.as_view(), name="platform-auth-me"),
    path("auth/logout/", TokenLogoutAPIView.as_view(), name="platform-auth-logout"),
    # Workspace / nav
    path("workspace/navigation/", WorkspaceNavigationAPIView.as_view(), name="platform-workspace-navigation"),
    path("workspace/menu-sections/", WorkspaceMenuSectionListCreateAPIView.as_view(), name="workspace-menu-section-list"),
    path("workspace/menu-sections/<int:pk>/", WorkspaceMenuSectionDetailAPIView.as_view(), name="workspace-menu-section-detail"),
    path("workspace/menu-items/", WorkspaceMenuItemListCreateAPIView.as_view(), name="workspace-menu-item-list"),
    path("workspace/menu-items/<int:pk>/", WorkspaceMenuItemDetailAPIView.as_view(), name="workspace-menu-item-detail"),
    path("workspace/menu-access/", WorkspaceRoleMenuAccessListCreateAPIView.as_view(), name="workspace-menu-access-list"),
    path("workspace/menu-access/<int:pk>/", WorkspaceRoleMenuAccessDetailAPIView.as_view(), name="workspace-menu-access-detail"),
    # Users & roles
    path("users/", PlatformUserListAPIView.as_view(), name="platform-user-list"),
    path("users/<int:pk>/", PlatformUserDetailAPIView.as_view(), name="platform-user-detail"),
    path("users/<int:pk>/update/", PlatformUserUpdateAPIView.as_view(), name="platform-user-update"),
    path("users/<int:pk>/assign-roles/", PlatformUserRoleAssignmentAPIView.as_view(), name="platform-user-assign-roles"),
    path("roles/", PlatformRoleListAPIView.as_view(), name="platform-role-list"),
    path("roles/<int:pk>/", PlatformRoleDetailAPIView.as_view(), name="platform-role-detail"),
    path("permissions/", PlatformPermissionListAPIView.as_view(), name="platform-permission-list"),
    # Tenants
    path("tenants/", TenantListCreateAPIView.as_view(), name="tenant-list"),
    path("tenants/self/", TenantSelfAPIView.as_view(), name="tenant-self"),
    path("tenants/provision/", provision_tenant, name="tenant-provision"),
    path("tenants/<int:pk>/", TenantDetailAPIView.as_view(), name="tenant-detail"),
    path("tenants/<int:pk>/suspend/", suspend_tenant, name="tenant-suspend"),
    path("tenants/<int:pk>/activate/", activate_tenant, name="tenant-activate"),
    path("tenants/<int:pk>/branches/", TenantBranchListCreateAPIView.as_view(), name="tenant-branch-list"),
    path("tenants/<int:pk>/users/", TenantUserListAPIView.as_view(), name="tenant-user-list"),
    path("tenants/<int:pk>/users/invite/", TenantUserInviteAPIView.as_view(), name="tenant-user-invite"),
    path("tenants/<int:pk>/settings/", TenantSettingsAPIView.as_view(), name="tenant-settings"),
    path("tenants/<int:pk>/settings/test-smtp/", test_tenant_smtp, name="tenant-settings-test-smtp"),
    # Branches
    path("branches/<int:pk>/", TenantBranchDetailAPIView.as_view(), name="branch-detail"),
    # Modules
    path("modules/", ModuleDefinitionListAPIView.as_view(), name="module-list"),
    path("modules/<int:pk>/", ModuleDefinitionDetailUpdateAPIView.as_view(), name="module-detail"),
    # Plans & subscriptions
    path("plans/", SubscriptionPlanListCreateAPIView.as_view(), name="plan-list"),
    path("plans/<int:pk>/", SubscriptionPlanDetailAPIView.as_view(), name="plan-detail"),
    path("subscriptions/", TenantSubscriptionListCreateAPIView.as_view(), name="subscription-list"),
    path("subscriptions/<int:pk>/", TenantSubscriptionDetailAPIView.as_view(), name="subscription-detail"),
    path("subscriptions/<int:pk>/sync-modules/", subscription_sync_modules_action, name="subscription-sync-modules"),
    # Licenses
    path("licenses/", LicenseKeyListCreateAPIView.as_view(), name="license-list"),
    path("licenses/<int:pk>/", LicenseKeyDetailAPIView.as_view(), name="license-detail"),
    path("licenses/<int:pk>/activate/", activate_license_action, name="license-activate"),
    path("licenses/<int:pk>/validate/", validate_license_action, name="license-validate"),
    # Module activations
    path("module-activations/", TenantModuleActivationListCreateAPIView.as_view(), name="module-activation-list"),
    path("module-activations/<int:pk>/", TenantModuleActivationDetailAPIView.as_view(), name="module-activation-detail"),
    path("module-access/", tenant_module_access_overview, name="tenant-module-access"),
    # Integrations
    path("integrations/", IntegrationEndpointListCreateAPIView.as_view(), name="integration-list"),
    path("integrations/<int:pk>/", IntegrationEndpointDetailAPIView.as_view(), name="integration-detail"),
    path("integrations/health/", integration_health_overview, name="integration-health-overview"),
    path("indicators/source-registry/", indicator_source_registry_overview, name="indicator-source-registry-overview"),
    # Documents & backups
    path("documents/templates/", DocumentTemplateListCreateAPIView.as_view(), name="document-template-list"),
    path("documents/templates/<int:pk>/", DocumentTemplateDetailAPIView.as_view(), name="document-template-detail"),
    path("backups/policies/", BackupPolicyListCreateAPIView.as_view(), name="backup-policy-list"),
    path("backups/policies/<int:pk>/", BackupPolicyDetailAPIView.as_view(), name="backup-policy-detail"),
]
